### PR TITLE
AlienFlight F4 OpenSky receiver

### PR DESCRIPTION
**Pull request by MJ666**
Looks to be the linked boot loader repo make some problems with eclipse Git tools? Changes on Makefile.arch make this to compile on windows. Need to be checked if this will not break it on other platforms?

### CODE REVIEW

**Review by fishpepper — CHANGES_REQUESTED** [review]
please do not delete the arch/cc251x/bootloader submodule, could you undo this and submit it again?

**Comment by MJ666** [comment]
I will try again tonight. this will be part of the problem I see with eclipse Git tools and the linked boot loader repo.

**Comment by fishpepper** [comment]
ok. thanks! i develop under linux so the script for building and merging the bootloader could include some stuff that does not work under windows. But you really want to have that bootloader, it is so convenient to upgrade the receiver firmware through the betafligh configurator :)
Once you submit a pull request the travis continuous integration server tries to build them (see below, it failed for this one). So you know that it still builds under linux.

**Comment by MJ666** [comment]
All looks to be ok now for the PR. I needed to do some dirty tricks with Git Gui. Not sure if Eclipse is supporting the submodules properly. Have installed all the tools used by the Makefiles and this part looks to be working. Not sure if the updating of the boot loader via the script is working well? It looks to be it is only executed if the Makefile in the boot loader directory does not exists? This will not update an already exiting directory.

**Comment by MJ666** [comment]
May be the lines from link below should be getting target specific?

https://github.com/fishpepper/OpenSky/blob/master/main.h#L6-L17

Since an STM32F4 can not invert UART input and output the AlienFlight receiver need uninverted SBUS and telemetry.

**Review by fishpepper — APPROVED** [review]
adding the new aff4rx target

**Pull request merged**
