### PR TITLE
Add a note about the raspberry pi fork of CC2510Lib

### PR DESCRIPTION
**Pull request by jimmyw**
Hi @fishpepper.

I got stuck trying to flash my VDM5 with my Arduino. Not really sure why, but i did not manage the flash tool to communicate to the Arduino.

Instead i forked your code, and rewrite it to use a raspberry pi, and flash using its 3.3v gpio. This worked really good for me, and it is very speedy and required no voltage dividers. Now my microquad works perfect using S.BUS 👍 

If you want, you can add a note to your README about this, so other users also can try it out.

Thanks again for your work, and the d4r_porting looks promising. If i got time, i am going to try to flash my x4r, i guess it is very minor differences in hardware.

Keep up the good work!!

### CODE REVIEW

**Comment by hpcre** [comment]
Hello Jimmy,
I'm at the same position you're in and wish to use the rpi solution of possible.  Can you help me out with details of how I you did this?  Thanks!

**Comment by jimmyw** [comment]
Np. Read the README.md at https://github.com/jimmyw/CC2510Lib. It is as easy as connecting all 5 wires correctly :) Tell me if you need help.

**Comment by hpcre** [comment]
Yeah thanks a lot,  just saw your fork..

**Comment by jimmyw** [comment]
Good luck! Tell me if you succeed!

If you get read/write errors, try increase the serial delay in Python/cclib/ccraspberry.py:34 a little. I successfully flashed my VD5M with just 1us delay.

**Comment by fishpepper** [comment]
Hi!
Thanks for your work, i added this. Right now i am preparing more and more documentation on my blog (http://fishpepper.de/projects/opensky/). I will add more tutorials the next days.
I recently pushed my d4r_porting branch to the master, it should be really easy to add new targets now.
If you want to flash your x4r make a copy of the board/d4rii directory, add it to the main makefile and edit the config.h file in board/x4r. I would be happy to add this to Opensky!
There should be minimal hardware differences i guess..

**Pull request merged**
